#let impl = $arrow$
#let eqviv = $mid(arrow.l.r)$
#let MP = $M_PP$
#let neq = $eq.not$
#let models = $tack.r.double$
#let subs = $subset.eq$
#let tu = $top$
#let fal = $bot$
#let CsqP = $"Csq"_PP$
#let CsqL = $"Csq"_L$
#let VFP = $"VF"_PP$
#let sl = $chevron.l$
#let sr = $chevron.r$
#let cR = $cal(R)$
#let cF = $cal(F)$
#let cA = $cal(A)$
#let sig = $sl cR, cF sr$
#let ar = $"ar"$
#let struct = $sl A, cR^cA, cF^cA sr$
#let Var = $"Var"$
#let PH = $"PH"$
#let cB = $cal(B)$
#let cl = $cal(l)$
#let cln = $overline(cl)$
#let Th = $"Th"$
#let cV = $cal(V)$
#let amogus = text(font: "Noto Serif Sinhala", size: 0.85em, [$\u{0d9e}$])
